# This is a basic workflow to help you get started with Actions

name: Testing PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Run Unit Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [macOS-latest]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: change FE directory
        run: cd ./makeuphara-front-end
      - name: yarn install
        run: yarn install
      - name: yarn test
        run: yarn test
      - name: failed test
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pr_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pr_number,
              body: "테스트가 실패햇습니다!",
              event: "COMMENT"
          if: failure()
      - name: success testing
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pr_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pr_number,
              body: "테스트를 통과했습니다!",
              event: "COMMENT"
          if: success()
